# Generated by Django 3.1.7 on 2021-07-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tilte',
            new_name='tilteman',
        ),
    ]
