# Generated by Django 3.1.7 on 2021-07-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0002_auto_20210707_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tilteman',
            new_name='tilte',
        ),
    ]
